### ISSUE TITLE
Shall we keep a macro only repository?

### ISSUE THREAD

**Issue by blackcathj** [sPHENIX-Collaboration/macros#1]
This repository seems only contain some macros. 

Shall we move it to be part of the coresoftware repository, as an official macro directory to drive the core simulation. A good place could be 
coresoftware/simulation/g4simulation/macro/

**Comment by mccumbermike** [comment]
You should ask Chris. He was the advocate for the separate repository.

**Comment by blackcathj** [comment]
Thanks. Talked with Chris. Now I think it is good idea to keep it too. In this case, people do not need to checkout the whole coresoftware, in order to use the macros with the standard nightly-built lib.
